version: '2'
services:
  nginx:
    image: gjiehs/sandbox-nginx:0.2.0
    ports:
      - '80:80'
    volumes:
      - ./application:/var/www/html
    networks:
      - sd-net
  php:
    image: gjiehs/sandbox-php:0.1.0
    volumes:
      - ./application:/var/www/html
    networks:
      - sd-net
  redis:
    image: redis:alpine
    networks:
      - sd-net
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my-app
      MYSQL_USER: app-user
      MYSQL_PASSWORD: app-pass
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - sd-net
networks:
  sd-net:
    driver: 'bridge'
volumes:
  mysqldata:
    driver: 'local'
